// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gorm.io/gorm"
	"imp-backend/application/use_case/auth/login"
	"imp-backend/application/use_case/auth/signup"
	"imp-backend/application/use_case/user/list_user"
	"imp-backend/infrastructure/persistence/repository"
)

import (
	_ "github.com/swaggo/echo-swagger/example/docs"
)

// Injectors from injection.go:

func LoginHandler(db *gorm.DB) login.LoginHandler {
	authRepository := repository.NewAuthRepository(db)
	loginService := login.NewLoginService(authRepository)
	loginHandler := login.NewLoginHandler(loginService)
	return loginHandler
}

func SignupHandler(db *gorm.DB) signup.SignupHandler {
	authRepository := repository.NewAuthRepository(db)
	signupService := signup.NewSignupService(authRepository)
	signupHandler := signup.NewSignupHandler(signupService)
	return signupHandler
}

func ListUserHandler(db *gorm.DB) list_user.ListUserHandler {
	authRepository := repository.NewAuthRepository(db)
	listUserService := list_user.NewListUserService(authRepository)
	listUserHandler := list_user.NewListUserHandler(listUserService)
	return listUserHandler
}
